## Test with 1 dimension dataset

In [1]:
import sys
import numpy as np
import pandas as pd
from time import time
from sklearn.ensemble import IsolationForest
from sklearn.metrics import confusion_matrix
import iforest_D as IFD
import iForest_mean as IFMean
sys.path.append('../')
#sys.path.insert(0, '/datasets')
from datasets import datasets as datat
import eif # Need to install eif from pypi first : pip install eif

## Generals settings

In [2]:
max_samples = 256
n_trees = 100
threshold = 0.6

contamination = 0.1

## Chargement du jeu de données

In [3]:
dts = datat.synthetic_datasets()
#X_brut, y_transform = dts.OneD_V1_0()
X_brut, y_transform, fulldataset = dts.OneD_V1_1()
#X_brut, y_transform, fulldataset = dts.OneD_V2()
#X_brut, y_transform, fulldataset = dts.TwoD_V1_0()
#X_brut, y_transform, fulldataset = dts.TwoD_V1_1()
#X_brut, y_transform, fulldataset= dts.TwoD_V2()
X_brut.describe()

Columns number = 2


0
count  1516.000000
mean      0.032098
std       1.107025
min      -3.334118
25%      -0.692580
50%      -0.034028
75%       0.649778
max       6.867883

In [4]:
X_brut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1516 entries, 0 to 1515
Data columns (total 1 columns):
0    1516 non-null float64
dtypes: float64(1)
memory usage: 12.0 KB


## Execution of scikit learn IForest on the dataset

In [5]:
func_skIF = IsolationForest(max_samples=max_samples, n_estimators=n_trees, contamination=contamination, behaviour="new")
func_skIF.fit(X_brut)
func_skIF_y_pred_IF = func_skIF.predict(X=X_brut)
# Matrice de confusion
print("Scikit learn IForest Confusion matrice")
#ttn, tfp, tfn, ttp = confusion_matrix(y_transform_Shuttle, MS_y_pred_IF_Shuttle).ravel()
print(confusion_matrix(y_transform, func_skIF_y_pred_IF))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/_iforest.py:248: FutureWarning: 'behaviour' is deprecated in 0.22 and will be removed in 0.24. You should not pass or set this parameter.
  FutureWarning


Scikit learn IForest Confusion matrice
[[  15    0]
 [ 137 1364]]


## Test avec LOF

In [6]:
from sklearn.neighbors import LocalOutlierFactor
# Instanciation, fit and predict on Shuttle
func_LOF = LocalOutlierFactor(novelty = True)
func_LOF.fit(X_brut)
y_pred_LOF = func_LOF.predict(X_brut)

# Matrice de confusion
#ttn, tfp, tfn, ttp = confusion_matrix(y_transform_Shuttle, MS_y_pred_IF_Shuttle).ravel()
print(confusion_matrix(y_transform, y_pred_LOF))

[[  15    0]
 [   7 1494]]


## Execution of IForest_D on the dataset

In [7]:
func_IFD = IFD.IsolationForest(sample_size = max_samples, n_trees=n_trees)
func_IFD.fit(X_brut)
IFD_y_pred_IF, IFD_y_scores_IF = func_IFD.predict(X=X_brut, threshold=threshold)
# Matrice de confusion
print("IForest_D Confusion matrice")
#ttn, tfp, tfn, ttp = confusion_matrix(y_transform_Shuttle, MS_y_pred_IF_Shuttle).ravel()
print(confusion_matrix(y_transform, IFD_y_pred_IF))

IForest_D Confusion matrice
[[  15    0]
 [ 103 1398]]


## Execution of IForest_Mean on the dataset

In [8]:
func_IFMean = IFMean.IsolationForest(sample_size = max_samples, n_trees=n_trees)
func_IFMean.fit(X_brut)
IFMean_y_pred_IF = func_IFMean.predict(X=X_brut, threshold=threshold)
# Matrice de confusion
print("IForest_D Confusion matrice")
#ttn, tfp, tfn, ttp = confusion_matrix(y_transform_Shuttle, MS_y_pred_IF_Shuttle).ravel()
print(confusion_matrix(y_transform, IFMean_y_pred_IF))

IForest_D Confusion matrice
[[  15    0]
 [1501    0]]


### Execution Of EIF on dataset

EIF don't work for One dimensionnal dataset, try to see if it is cause of EIF implementation on Pypi or cause of EIF principle

In [13]:
X_brut_numpy = X_brut.to_numpy()

#### Extented 1

In [14]:
F0  = eif.iForest(X_brut_numpy, ntrees=n_trees, sample_size=max_samples, ExtensionLevel=0)
S0 = F0.compute_paths(X_in=X_brut_numpy)
P0 = np.where(S0>=threshold,-1,1)

# Matrice de confusion
#ttn, tfp, tfn, ttp = confusion_matrix(y_transform_Shuttle, MS_y_pred_IF_Shuttle).ravel()
print(confusion_matrix(y_transform, P0))

[[  15    0]
 [  63 1438]]


#### Extented 2

In [ ]:
F1  = eif.iForest(X_brut_numpy, ntrees=n_trees, sample_size=max_samples, ExtensionLevel=1)
S1 = F1.compute_paths(X_in=X_brut_numpy)
P1 = np.where(S1>=threshold,-1,1)

# Matrice de confusion
#ttn, tfp, tfn, ttp = confusion_matrix(y_transform_Shuttle, MS_y_pred_IF_Shuttle).ravel()
print(confusion_matrix(y_transform, P1))

In [ ]:
import random
min_x = -0.45
max_x =  1
min_x + random.betavariate(0.5, 0.5) * (max_x - min_x)

In [ ]:
random.uniform(min_x, max_x)

In [ ]:
P1.mean()